# Generated by Django 4.2 on 2023-04-19 15:17

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hight', models.FloatField(null=True, verbose_name='Высота бокса')),
                ('length', models.FloatField(null=True, verbose_name='Длина бокса')),
                ('width', models.FloatField(null=True, verbose_name='Ширина бокса')),
                ('rental_price', models.PositiveBigIntegerField(null=True, verbose_name='Стоимость суточной аренды')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_start_date', models.DateField(blank=True, verbose_name='Дата начала контракта')),
                ('order_end_date', models.DateField(blank=True, verbose_name='Дата закрытия заказа')),
                ('cargo_size', models.FloatField(verbose_name='Объём груза')),
                ('cargo_weight', models.FloatField(verbose_name='Вес груза')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boxes', to='tg_bot.box', verbose_name='Номер бокса')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='ID пользователя')),
                ('name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Имя пользователя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='tg_bot.order', verbose_name='Заказы')),
            ],
        ),
    ]
