# Generated by Django 4.2 on 2023-04-21 14:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100, verbose_name='Размер бокса')),
                ('rental_price', models.PositiveBigIntegerField(null=True, verbose_name='Стоимость суточной аренды')),
            ],
            options={
                'verbose_name': 'Бокс',
                'verbose_name_plural': 'Боксы',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='ID пользователя')),
                ('name', models.CharField(blank=True, db_index=True, max_length=200, verbose_name='Имя пользователя')),
                ('address', models.CharField(blank=True, db_index=True, max_length=300, verbose_name='Адрес пользователя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Номер телефона')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_time', models.IntegerField(null=True, verbose_name='Срок хранения (дни)')),
                ('order_start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала контракта')),
                ('delivery_time', models.DateField(blank=True, null=True, verbose_name='Дата доставки')),
                ('order_end_date', models.DateField(blank=True, null=True, verbose_name='Дата закрытия заказа')),
                ('cargo_size', models.CharField(blank=True, max_length=50, null=True, verbose_name='Объём груза')),
                ('cargo_weight', models.CharField(blank=True, max_length=50, null=True, verbose_name='Вес груза')),
                ('need_delivery', models.CharField(blank=True, default='Да', max_length=10, verbose_name='Необходимость доставки')),
                ('conformation', models.BooleanField(default=False, verbose_name='Подтверждение заказа')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнение заказа')),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tg_bot.box', verbose_name='Номер бокса')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tg_bot.customer', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
